version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:21-jdk  # Specify the Docker image with Java 21
    working_directory: /workspace

jobs:
  test:
    executor: java-executor
    steps:
      - checkout  # Checkout the code
      - run:
          name: Install Dependencies
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew test  # Run your tests

workflows:
  version: 2
  test:
    jobs:
      - test