version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout  # Checkout the code

      # Cache Gradle dependencies to speed up future builds
      - restore_cache:
          keys:
            - gradle-deps-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - gradle-deps-{{ checksum "build.gradle" }}
            - gradle-deps-

      # Install dependencies and tools (including xargs)
      - run:
          name: Install Dependencies and Tools
          command: |
            apt-get update && apt-get install -y findutils  # Install xargs and other utilities
            ./gradlew --no-daemon dependencies  # Install project dependencies

      # Build the project
      - run:
          name: Build Project
          command: ./gradlew build --no-daemon

      # Run Tests
      - run:
          name: Run Tests
          command: ./gradlew test --no-daemon

      # Save the cache of Gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-deps-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}

      - store_test_results:
          path: build/test-results/test

workflows:
  version: 2
  test:
    jobs:
      - test